version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore(github-actions)
    groups:
      github-actions:
        patterns: ["*"]
