-   id: biome-ci
    name: biome ci
    entry: biome ci --files-ignore-unknown=true --no-errors-on-unmatched
    language: node
    types: [text]
    files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?)$"
-   id: biome-check
    name: biome check
    entry: biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
    language: node
    types: [text]
    files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?)$"
-   id: biome-format
    name: biome format
    entry: biome format --write --files-ignore-unknown=true --no-errors-on-unmatched
    language: node
    types: [text]
    files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?)$"
-   id: biome-lint
    name: biome lint
    entry: biome lint --write --files-ignore-unknown=true --no-errors-on-unmatched
    language: node
    types: [text]
    files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?)$"
